### ISSUE TITLE
add logging msgs everywhere

### ISSUE THREAD

**Issue by celery6** [waterloo-rocketry/cansw_processor_stm#22]
title.

**Comment by Joe-Joe-Joe-Joe** [comment]
There are a bunch of logging messages everywhere. It would be good for someone to pick through and figure out which ones belong there for the final product

**Comment by celery6** [comment]
might be interesting to log freertos runtime stats at the end of flight
https://www.freertos.org/rtos-run-time-stats.html
we already have it set up, just need to call the function and log the string it gives

**Comment by Joe-Joe-Joe-Joe** [comment]
this should either have more concrete deliverable or be closed
