### ISSUE TITLE
add live status trackers in each task

### ISSUE THREAD

**Issue by celery6** [waterloo-rocketry/cansw_processor_stm#31]
for example, a static var in canhandler.c that can be updated if something during canhandler errors out or times out, etc. This var can be checked periodically thru otits. Could help to check that tasks are actually running and arent failing to read queues

**Comment by celery6** [comment]
also track # of dropped logs as a static var

**Comment by Joe-Joe-Joe-Joe** [comment]
this seems like otits scope? I think you were working on this for logging? either way should not be for every task until we prove it out elsewhere

**Comment by celery6** [comment]
stuff is close enough. this is not critical for anything
