### ISSUE TITLE
build pipeline

### ISSUE THREAD

**Issue by celery6** [waterloo-rocketry/cansw_processor_stm#33]
title. build code in github pipeline. it's slightly concerning the amt of times we push that doesn't build (i am guilty of this many times :skullemoticon)

**Comment by Joe-Joe-Joe-Joe** [comment]
How do you do that

**Comment by Joe-Joe-Joe-Joe** [comment]
Apparently this is how https://github.com/xanderhendriks/stm32-sample-application
