### ISSUE TITLE
SD card logging is slow

### ISSUE THREAD

**Issue by Joe-Joe-Joe-Joe** [waterloo-rocketry/cansw_processor_stm#40]
The logging API gets bogged down pretty quick to the point it can't keep up with demand. Upping the clock speed of the SDMMC peripheral may fix this, so this should be increased and then log.c load tested (I would just run the debugger and break at the spot in logGeneric where we check to see if the buffer is already full)

**Comment by celery6** [comment]
the one time i tested it was writing 1 buffer (8192 byte) per 10 ms. 1 buffer is 32 fullize msgs, so this is like 3khz msgs/sec which shiuldnt be bogged down already? is the math wrong or smth else issue

**Comment by Joe-Joe-Joe-Joe** [comment]
This is with 25 Mhz SDMMC clock and trying to write 1 log message every 1 tick
![image](https://github.com/waterloo-rocketry/cansw_processor_stm/assets/25694245/e9cfa692-ef71-45ae-813b-04a1f4ddb585)

This is with 100 MHz
![image](https://github.com/waterloo-rocketry/cansw_processor_stm/assets/25694245/51836a21-f783-4c3e-a36c-5f3e0977a6f0)

Not exactly sure where the issue lies but its bottlenecking at almost exactly 10ms between messages

**Comment by celery6** [comment]
ill look at this issue more this tmr

**Comment by celery6** [comment]
this might be being bottlenecked at `logGeneric()` which takes between 1 to 6 ticks depending on msg length..
and only 1 logGeneric can run at once so thats like 1msg per 5 ticks which is way less than SD card write speed of ~3.2 msgs per 1 tick

**Comment by celery6** [comment]
assume that 1 logGeneric takes 3 ms to complete (not including waiting in line), that's like 3.3 full size msgs per 10 ticks which doesnt seem ideal :skull-emoticon (full size is 256 chars including everything)

**Comment by Joe-Joe-Joe-Joe** [comment]
this has become a bit of a rabbit hole and this issue is no longer actionable. closing.

**Comment by Joe-Joe-Joe-Joe** [comment]
I missed that this was covered in #65 
Make sure to reference issues in your PR :bulbaowo:
