### ISSUE TITLE
Clean up includes & externs

### ISSUE THREAD

**Issue by Joe-Joe-Joe-Joe** [waterloo-rocketry/cansw_processor_stm#44]
There are a bunch of files with extraneous and/or misplaced `#include`s. These could be cleaned up a bit. Same with `extern`s

**Comment by celery6** [comment]
im lumping into this one:
- adjust task stack sizes?
- check task creation status and all init statuses
- whatever other software cleanup

**Comment by Joe-Joe-Joe-Joe** [comment]
Can we roll #22 into this also?

**Comment by Joe-Joe-Joe-Joe** [comment]
this was rolled into #68 instead, closing
