### ISSUE TITLE
Figure out max current draw

### ISSUE THREAD

**Issue by Joe-Joe-Joe-Joe** [waterloo-rocketry/cansw_processor_stm#48]
Currently health checks triggers on like 500 mA of current draw but I have never seen us draw more than like 220. So we should probably figure out what constitutes a "concerning" amount of current

**Comment by Armaan-Sengupta** [comment]
I will determine this simultaneously when we do mechanical load testing

**Comment by Armaan-Sengupta** [comment]
Oh you wanted me to check it using the board, yea idk how to do that, I was fully planning on using the power supply, this is a health checks thing right, I can try to figure it out, but idk if I can commit to taking it on

**Comment by Joe-Joe-Joe-Joe** [comment]
see also #67
