### ISSUE TITLE
VN needs to be configured for in rocket config

### ISSUE THREAD

**Issue by Armaan-Sengupta** [waterloo-rocketry/cansw_processor_stm#50]
Offsets for the position of the VN mounting in the rocket as well as offsets between the VN and the antennas need to be configured

**Comment by Joe-Joe-Joe-Joe** [comment]
Position offset is negligible. I think my last PR to get the filter working also fixed the orientation, at least the pitch - when we are pointing "rocket up", we get +90, and when we are sideways we are at 0. So I'm going to close this
