### ISSUE TITLE
redo vn data logging using binary struct dump to sd card files

### ISSUE THREAD

**Issue by celery6** [waterloo-rocketry/cansw_processor_stm#61]
In response to #40 .

Overview: since the VN data is known and limited and numerical, we can put each packet of VN data into a nice packed struct. Then, populate a large array of these structs to dump to the SD card (same way logger does arrays of chars) 

advantages over logging as string: 1) printf family functions take fucking forever theyre very not embedded + high freq friendyly :sku;. 2) vn data is predicable and numerical. 3) no one likes dealing with strings in embedded.

implementation thoughts
- this should still be in the logger module, probably something like `logVN()`
- log to a diff file than logger
  - maybe even log each new buffer to a new file for safety so if one file flops then others can still be read
- the vn struct needs to indicate which type it is (gps data, state, etc)
- REDUNDANCY HOW
  - idk yet. needs ways to ensure we can parse it in case a byte gets dropped etc etc

**Comment by celery6** [comment]
aiming to implement some drft of this by saturday? at least to see how easdily doable. if bad then we can go back to overoptimizing logger to death

**Comment by celery6** [comment]
#40 
https://github.com/waterloo-rocketry/cansw_processor_stm/pull/65
Binary logging may be avoided if this concurrent logging thing proves to be fast enough

**Comment by Joe-Joe-Joe-Joe** [comment]
> this concurrent logging thing proves to be fast enough

It did!
