### ISSUE TITLE
VN GNSS Compass / INS does not report a solution despite GNSS raw data getting a fix

### ISSUE THREAD

**Issue by Armaan-Sengupta** [waterloo-rocketry/cansw_processor_stm#63]
The INS does not output a solution despite the GNSS having a fix, it says the INS is disabled, but I dont know how to enable it. Page 12 in the ICD might be a clue (Set Initial Heading)?

**Comment by Joe-Joe-Joe-Joe** [comment]
The GNSS was also unable to get a fix during WDR

**Comment by Joe-Joe-Joe-Joe** [comment]
This has been resolved. Turns out you have to run the VN300 with both antennas for the INS to function at all. Testing with both antennas yielded success, INS starts up in about 15 minutes.
